renderer : mediawiki
input_path :
output_path :
doc_title:
base_path:
collapse_content_level: 2
collapse_pages_level: 2
create_index: (True/False)
export_format: text
export_single_pages: (True/False)
export_pages_tree: (True/False)
export_book_page: (True/False)
print_preparsed_tex: (True/False)
lang: (Look at i18n.yaml)
plugins: [MathCheck]
plugins_configs:
    math_check_online:
        threads: 3
        domain: wikitolearn.org
